psy_test/urls.py
from django.contrib import admin
from django.urls import path
from testing import views
from django.conf import settings
from django.conf.urls.static import static
from testing.views import EditResult, EditTest, DeleteTest, DeleteQuestion
from numerology.views import destiny_number, soul_number, pithagor_matrix

urlpatterns = [
    # general URLs

    path("admin/", admin.site.urls),
    path("register/", views.register, name='register'),
    path("login/", views.auth, name='login'),
    path("home/", views.index, name='home'),
    path("logout/", views.log_out, name='log_out'),

    # testing_app urls

    path("tests_list/", views.tests_list, name='tests-list'),
    path("<int:test_id>/test_info/", views.test_info, name='test_info'),
    path("edit_question/<int:test_id>/<int:question_id>/", views.edit_question, name='edit_question'),
    path('create_test/', views.create_test, name='create_psytest'),
    path('create_questions/<int:test_id>/', views.create_questions, name='create_questions'),
    path('create_results/<int:test_id>/', views.create_test_results, name='create_results'),
    path('edit_test/<pk>/', EditTest.as_view(), name='edit_test'),
    path('edit_result/<pk>/', EditResult.as_view(), name='edit_result'),
    path('delete_test/<pk>/', DeleteTest.as_view(), name='delete_test'),
    path('delete_question/<pk>', DeleteQuestion.as_view(), name='delete_question'),
    path('take_test/<int:test_id>/', views.take_test, name='take_test'),
    path('tests/results/<int:result_id>/', views.get_results, name='get_results'),
    path('home/your_results', views.your_results, name='your_results'),
    path('home/your_results_details/<int:result_id>', views.your_results_details, name='your_results_details'),

    # numerology_app urls
    path('numerology/destiny_number', destiny_number, name='destiny_number'),
    path('numerology/soul_number', soul_number, name='soul_number'),
    path('numerology/pithagor_matrix', pithagor_matrix, name='pithagor_matrix'),



]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

testing/models.py
from django.db import models
from customuser.models import CustomUser

class TestCategory(models.Model):
    title = models.CharField(max_length=128)
    description = models.TextField(max_length=1024)

    def __str__(self):
        return self.title

class PsyTest(models.Model):
    title = models.CharField(max_length=128)
    description = models.TextField(max_length=1024)
    author = models.CharField(max_length=128)
    added_by = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    category = models.ForeignKey(TestCategory, on_delete=models.CASCADE)
    addition_date = models.DateField(auto_now=True)

    def __str__(self):
        return self.title


class Question(models.Model):
    test = models.ForeignKey(PsyTest, on_delete=models.CASCADE)
    description = models.TextField(max_length=256)
    
    def __str__(self):
        return self.description

class Option(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    description = models.CharField(max_length=128)
    points = models.IntegerField(default=0)
    
    def __str__(self):
        return self.description
    
    
class TestResult(models.Model):
    test = models.ForeignKey(PsyTest, on_delete=models.CASCADE)
    condition_max = models.PositiveIntegerField()
    condition_min = models.PositiveIntegerField()
    description = models.TextField(max_length=2048)
    
    def __str__(self):
        return self.description

class PersonalResult(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    test = models.ForeignKey(PsyTest, on_delete=models.CASCADE)
    result = models.ForeignKey(TestResult, on_delete=models.CASCADE)
    score = models.PositiveIntegerField()
    date = models.DateTimeField(auto_now=True)
    answers =models.TextField(max_length=4096)

    def __str__(self):
        return f"{self.user} - {self.test}"

testing/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.shortcuts import redirect
from django.http import HttpResponseBadRequest, HttpResponseRedirect
from django.urls import reverse_lazy
from django.urls import reverse
from django import forms
from django.views.generic.edit import UpdateView
from django.views.generic.edit import DeleteView
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.forms.models import inlineformset_factory
from django.http import HttpResponseNotAllowed, HttpResponse
from django.contrib.auth import authenticate, login, logout
from django.forms import modelformset_factory


from testing.filters import TestFilter
from .models import TestCategory, Question, PsyTest, TestResult, PersonalResult, Option
from .forms import PsyTestForm, QuestionForm, OptionForm, TestResultForm, UserForm, UserEditForm, OptionFormSet

def index(request):
    return render(request, 'testing/index.html')


def register(request):
    if request.method == 'POST':
        user_form = UserForm(request.POST)
        if user_form.is_valid():
            user = user_form.save()
            login(request, user)
            return redirect('/home')
    else:
        user_form = UserForm()
    return render(request, 'testing/auth/register.html', {'user_form': user_form})


def auth(request):
    if request.method == 'POST':
        email = request.POST['email']
        password = request.POST['password']
        user = authenticate(request, email=email, password=password)
        if user is not None:
            login(request, user)
            messages.success(request, f'Welcome, {user}! ')
            return redirect('/home')
        else:
            messages.info(request, 'Something went wrong. Please try again!')
            return redirect('/login')
    else:
        return render(request, 'testing/auth/login.html')
    

@login_required
def log_out(request):
    logout(request)
    messages.info(request, "Logged out successfully!")
    return redirect("home")


def create_test(request):
    if request.user.is_superuser:
        user = request.user
        if request.method == 'POST':
            test_form = PsyTestForm(request.POST)
            if test_form.is_valid():
                user = user
                test = test_form.save(commit=False)
                test.added_by = user
                test.save()
                            
                messages.success(request, 'Test created')
                return redirect('create_questions', test_id = test.id)
        else:
            test_form = PsyTestForm(initial= {'added_by': request.user,
                                              })
        return render(request, 'testing/creating/create_test.html', {
            'test_form': test_form,
        })
    else:
        return HttpResponse(request, 'You have no rights')

def create_questions(request, test_id):
    if request.user.is_superuser:
        test = PsyTest.objects.get(id=test_id)
        if request.method == 'POST':
            question_form = QuestionForm(request.POST)
            OptionFormSet = inlineformset_factory(Question, Option, form=OptionForm, can_delete=True, extra=6)
            option_formset = OptionFormSet(request.POST)

            if question_form.is_valid() and option_formset.is_valid():
                question = question_form.save(commit=False)
                question.test = test
                question.save()

                options = option_formset.save(commit=False)
                for option in options:
                    option.question = question
                    option.save()

                action = request.POST.get('action', 'back')
                question_number = int(request.POST.get('question_number', 1))

                if action == 'add':
                    question_number += 1
                    question_form = QuestionForm(initial={'test': test, 'number': question_number})
                    option_formset = OptionFormSet(queryset=Option.objects.none())
                if action == 'results':
                    return redirect('create_results', test_id)
                elif action == 'finish':
                    return redirect('tests-list')
            else:
                question_number = int(request.POST.get('question_number', 1))
        else:
            question_number = 1
            question_form = QuestionForm(initial={'test': test, 'number': question_number})
            OptionFormSet = inlineformset_factory(Question, Option, form=OptionForm,can_delete=True, extra=6)
            option_formset = OptionFormSet(queryset=Option.objects.none())

        return render(request, 'testing/creating/create_questions.html', context={'test': test, 'question_form': question_form, 'option_formset': option_formset, 'question_number': question_number})
    else:
        return HttpResponse(request, 'You have no rights')


def create_test_results(request, test_id):
    if request.user.is_superuser:
        test = PsyTest.objects.get(id=test_id)
        test_result_form = TestResultForm()
        if request.method == 'POST':
            test_result_form = TestResultForm(request.POST)
            if test_result_form.is_valid():
                result = test_result_form.save(commit=False)
                result.test = test
                result.save()
                messages.success(request, 'Result created')
            return redirect('create_results', test_id=test_id)
        
        result_number = test.testresult_set.count() + 1
        test_result_form = TestResultForm(initial={'test': test})
        
        return render(request, 'testing/creating/create_results.html', {
            'test': test,
            'test_result_form': test_result_form,
            'result_number': result_number
        })
    else:
        return HttpResponse(request, 'You have no rights')
    

class EditTest(UpdateView):
    model = PsyTest
    fields = ['title', 'description', 'author', 'category']
    template_name = 'testing/editing/edit_test.html'

    def get_success_url(self):
        return reverse_lazy('test_info', kwargs={'test_id': self.object.pk})


class EditResult(UpdateView):
    model = TestResult
    fields = ['description', 'condition_min', 'condition_max']
    template_name = 'testing/editing/edit_result.html'

    def get_success_url(self):
        return reverse('test_info', kwargs={'test_id': self.object.test.id})


class DeleteTest(DeleteView):
    model = PsyTest
    success_url = '/tests_list'
    template_name = 'testing/editing/delete_test.html'

@login_required
def tests_list(request):
    f = TestFilter(request.GET, queryset=PsyTest.objects.all())
    return render(request, 'testing/psytesting/tests_list.html', {'filter': f})


@login_required
def test_info (request, test_id):
    test = PsyTest.objects.get(id = test_id)
    questions = Question.objects.filter(test = test)
    options = Option.objects.filter(question__in=questions)  # Получаем все связанные объекты Option
    results = TestResult.objects.filter(test=test)
    if request.method == 'GET':
        return render (request, 'testing/psytesting/test_info.html', {
            'test': test,
            'title': test.title,
            'category': test.category,
            'author': test.author,
            'description': test.description,
            'questions': questions,
            'options': options, 
            'results': results
            })
    
def edit_question(request, test_id, question_id):
    if request.user.is_superuser:
        test = PsyTest.objects.get(id = test_id)
        question = Question.objects.get(id = question_id)
        if request.method == 'POST':
            question_form = QuestionForm(request.POST, instance=question)
            OptionFormSet = inlineformset_factory(Question, Option, form=OptionForm, extra = 0, widgets = {
            'description': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Input description', 'rows': 2}),
            'points': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Input points for option', 'rows': 2, 'style': 'width: 100%'})
            })
            option_formset = OptionFormSet(request.POST or None, instance=question)

            if question_form.is_valid() and option_formset.is_valid():
                question = question_form.save(commit=False)
                question.test = test
                question.save()

                options = option_formset.save(commit=False)
                for option in options:
                    option.question = question
                    option.save()
            
            return HttpResponseRedirect(reverse('test_info', args=[test.pk]))

        else:
            question_form = QuestionForm(initial={'test': test, 'question': question, 'description': question.description})
            OptionFormSet = inlineformset_factory(Question, Option, form=OptionForm, extra = 0)
            option_formset = OptionFormSet(instance=question, initial= {'id': question.pk,})

        return render(request, 'testing/editing/edit_question.html', context={'test': test, 'question': question, 'question_form': question_form, 'option_formset': option_formset,})
    else:
        return HttpResponse(request, 'You have no rights')


class DeleteQuestion(DeleteView):
    model = Question
    template_name = 'testing/editing/delete_question.html'
    def get_success_url(self):
        return reverse_lazy('test_info', kwargs={'test_id': self.object.pk})



@login_required
def take_test(request, test_id):
    test = PsyTest.objects.get(id=test_id)
    questions = test.question_set.all()
    options = Option.objects.filter(question__in=questions)
    user = request.user

    if request.method == 'POST':
        score = 0
        for question in questions:
            option_id = request.POST.get(f'question_{question.id}')
            if option_id is not None:

testing/templates/testing/psytesting/get_results.html
{% extends 'testing/base.html' %}
{% block content %}
<h3 class="display-6" >This is your {{test}} results: </h3>

<p class="lead">
  Test title: {{test}}
</p>
<p class="lead">
  Your score: {{score}}
</p>
<p class="lead">
  Resume: {{resume}}
</p>
{% endblock %}

testing/templates/testing/psytesting/take_test.html
{% extends 'testing/base.html' %}
{% block content %}
<form method="post">
  {% csrf_token %}
  <input type="hidden" name="test_id" value="{{ test.id }}">
  <input type="hidden" name="questions" value="{{ questions }}">
  <input type="hidden" name="options" value="{{ options }}">
  {% for q in questions %}
  <div class="container-fluid">
    <p class="fw-bolder fs-5"  style="margin-left: 0.5em; margin-top: 0.5em ">
      {{ q.description }}  </p>
      {% for o in q.option_set.all %}
      <div class="form-check" style="padding-top: 0.5em;">
        <input class="form-check-input" type="radio" name= "question_{{ q.id }}" id="flexRadioDefault1" value="{{ o.id }}">
        <label class="form-check-label" for="flexRadioDefault1">{{ o.description }}
        
        </label>
      </div>
        {% comment %} <input type="radio" name="question_{{ q.id }}" value="{{ o.id }}">{{ o.description }} {% endcomment %}
      {% endfor %}
    </div>

  {% endfor %}

  <div class="d-grid gap-2" style="padding-top: 1.5em;">
  <button type="submit" class="btn btn-dark" >Submit</button>
  </div>
</form>

{% endblock %}

testing/templates/testing/psytesting/test_info.html
{% extends 'testing/base.html' %}

{% block content %}
  <h3 class="display-6">Test "{{ title }}"</h3>
  <p class="lead"> Category: {{ category }}</p>
  <p class="lead"> Author: {{ author }}</p>
  <p class="lead"> Description: {{ description }}</p>
  
  {% for question in questions %}
    <div class="card">
      <div class="card-header">
        Question {{ forloop.counter }}:     
      </div>
      <div class="card-body">
        <h5 class="card-title">{{ question.description }}</h5>
        <br>
        {% for option in question.option_set.all %}
          <p class="card-text"> <b>Option {{forloop.counter}}: </b>{{ option.description }}</p>
          <p class="card-text"><em>Points:</em> {{ option.points }}</p>
        {% endfor %}
        <a href="{% url 'edit_question' test_id=test.id question_id=question.id %}" class="btn btn-dark">Edit question</a>
        <a href="{% url 'delete_question' pk=question.id %}" class="btn btn-dark">Delete question</a>
      </div>
    </div>
    <br>
    {% endfor %}

  
    {% for result in results %}
    <div class="card">
      <div class="card-header">
        Result {{ forloop.counter }}:     
      </div>
      <div class="card-body">
        <h5 class="card-title">{{ result.description }}</h5>
        <p class="card-text"> <em>Condition lower to: {{result.condition_max}}</em></p>
        <p class="card-text"> <em>Condition greater to: {{result.condition_min}}</em></p>
        <a href="{% url 'edit_result' pk=result.pk %}" class="btn btn-dark">Edit result</a>
      </div>
    </div>
    <br>
  {% endfor %}
{% endblock %}

testing/templates/testing/psytesting/tests_list.html
{% extends 'testing/base.html' %}
{% block content %}
  <h3 class="display-6"> Tests List</h3>
  <form method="GET">
    {% csrf_token %}
    {{filter.form.as_table}}
    <button type="submit" class="btn btn-dark">Search</button>
    <a class="btn btn-dark" href=" {% url 'create_psytest' %}" role="button"> + Create test</a>
  </form>
  <div class="table-responsive">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Title</th>
          <th>Category</th>
          <th>Author</th>
          <th>Addition date</th>
        </tr>
      </thead>
      <tbody>
        {% for obj in filter.qs %}
          <tr>
            <td>{{ obj.title }}</td>
            <td>{{ obj.category }}</td>
            <td>{{ obj.author }}</td>
            <td>{{ obj.addtion_date }}</td>
            <td>
              <div class="dropdown">
                <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Actions
                </button>
                <ul class="dropdown-menu">
                  <li><a href="{% url 'take_test' test_id=obj.id %}" class="dropdown-item">Pass</a></li>
                  {% if request.user.is_superuser %}
                    <li><a href="{% url 'edit_test' pk=obj.id %}" class="dropdown-item">Edit</a></li>
                    <li><a href="{% url 'delete_test' pk=obj.id %}" class="dropdown-item">Delete</a></li>
                  {% endif %}
                </ul>
              </div>
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}

testing/templates/testing/psytesting/your_results.html
{% extends "testing/base.html" %}

{% block content %}
  <h3> Here you can check all your results</h3>
  <form method="GET">
  <div class="table-responsive">
  <table class="table table-striped">
    <thead>
      <tr>
      <th>Title</th>
      <th>Category</th>
      <th> Author </th>
      <th> Score </th>
      </tr>
    </thead>
    <tbody>
    {% for obj in results %}
    <td>{{ obj.test.title }}</td>
    <td>{{ obj.test.category }}</td>
    <td>{{ obj.test.author }}</td>
    <td>{{ obj.score}}</td>
    <td> <a href= {% url 'your_results_details' result_id=obj.id %} class="btn btn-dark btn-sm active" role="button"> Details </td>
    </tr>
  {% endfor %}
  </tbody>
  </table>
  </div>
{% endblock %}

testing/templates/testing/psytesting/your_results_details.html
{% extends "testing/base.html" %}

{% block content %}
<h3 class="display-6" >This is your {{test}} results: </h3>

<p class="lead">
  <b>Test</b>: {{test}}
</p>
<p class="lead">
  <b>Category</b>: {{test.category}}
</p>
<p class="lead">
  <b>Author</b>: {{test.author}}
</p>
<p class="lead">
  <b>Your score</b>: {{score}}
</p>
<p class="lead">
  <b>Resume</b>: {{resume}}
</p>
{% endblock %}